version: "3.8"
services:
  sdn:
    tty: true
    stdin_open: true
    container_name: sdn
    hostname: sdn
    build: ./sdn

  src:
    tty: true
    stdin_open: true
    container_name: src
    hostname: src
    build: ./src

  node_1:
    tty: true
    stdin_open: true
    container_name: node_1
    hostname: node_1
    build: ./vnfs

  node_2:
    tty: true
    stdin_open: true
    container_name: node_2
    hostname: node_2
    build: ./vnfs

  node_3:
    tty: true
    stdin_open: true
    container_name: node_3
    hostname: node_3
    build: ./vnfs

  dst:
    tty: true
    stdin_open: true
    container_name: dst
    hostname: dst
    build: ./dst
